name: Run Pytest Tests with PDM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Cache PDM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pdm
        key: ${{ runner.os }}-pdm-${{ hashFiles('**/pyproject.toml', '**/pdm.lock') }}
        restore-keys: |
          ${{ runner.os }}-pdm-

    - name: Install dependencies
      run: |
        pdm install --dev
      env:
        PDM_IGNORE_SAVED_PYTHON: 1

    - name: Run tests
      run: |
        pdm run pytest
